const fs = require('fs');
const path = require('path');

const NEW_DATA = [
  {
    id: 125,
    name: "K-Guard",
    category: "Guard System",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "High",
    body_target: "Legs",
    notes: "A powerful modern open guard entry primarily used to expose the opponent's backside 50/50 for heel hook attacks. It relies on scooping under the opponent's knee and passing your leg over their hip.",
    common_setups: ["Opponent stands above your open guard", "Entering from closed guard via Williams guard position"],
    common_counters: ["Immediate backstep pass before the leg laces", "Pinning the scooping arm"]
  },
  {
    id: 126,
    name: "Octopus Guard",
    category: "Guard System",
    aka: [],
    skill_level: "Intermediate",
    gi_nogi: "Both (Equally)",
    risk_level: "Medium",
    body_target: "Back / Core",
    notes: "Created by Eduardo Telles, this guard wraps your arm over the opponent's far shoulder/lat from the bottom, misaligning their centerline and enabling easy back takes or sweeps.",
    common_setups: ["Opponent passes your half guard high", "Baiting an underhook and sneaking behind the shoulder"],
    common_counters: ["Stepping over the shoulder to counter-attack", "Aggressive cross-facing"]
  },
  {
    id: 127,
    name: "Squid Guard",
    category: "Guard System",
    aka: ["Matrix Guard", "Lapel Guard"],
    skill_level: "Advanced",
    gi_nogi: "Gi only",
    risk_level: "Low",
    body_target: "Core / Base",
    notes: "A complex lapel guard developed by Keenan Cornelius. You loop your opponent's lapel outside their leg and under their thigh to immobilize their movement completely.",
    common_setups: ["From open guard by pulling the opponent's lapel out", "From De La Riva foot position"],
    common_counters: ["Breaking the lapel grip early", "Dropping heavy hips to prevent the foot placement"]
  },
  {
    id: 128,
    name: "Williams Guard (Rat Guard)",
    category: "Guard System",
    aka: ["Rat Guard"],
    skill_level: "Intermediate",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Shoulders / Neck",
    notes: "A high closed guard variation where you lock your hands under your own leg (which is thrown over the opponent's shoulder), creating massive posture control to set up omoplatas and gogoplatas.",
    common_setups: ["Opponent defends a standard omoplata by posturing up", "From a high closed guard / rubber guard entry"],
    common_counters: ["Peeling the grip before it connects", "Stacking heavily onto the neck"]
  },
  {
    id: 129,
    name: "Shin-to-shin Guard",
    category: "Guard System",
    aka: [],
    skill_level: "Fundamental",
    gi_nogi: "Both (Equally)",
    risk_level: "Low",
    body_target: "Legs / Balance",
    notes: "A seated open guard entry where your shin connects flush against the opponent's shin, allowing you to intercept their forward movement and elevate them into Single Leg X or Asji-garami.",
    common_setups: ["Seated guard vs standing opponent approaching", "When an opponent steps into your space"],
    common_counters: ["Knee slicing quickly over the shin", "Backstepping to clear the connection entirely"]
  },
  {
    id: 130,
    name: "Quarter Guard",
    category: "Guard System",
    aka: ["Ankle trap"],
    skill_level: "Fundamental",
    gi_nogi: "Both (Equally)",
    risk_level: "High",
    body_target: "Ankle",
    notes: "A last-ditch defensive guard when the opponent has almost passed side control or mount, but you trap their ankle. Often used to dig for deep half guard.",
    common_setups: ["Defending a mount transition", "Failing a half-guard sweep and recovering the foot"],
    common_counters: ["Freeing the ankle with a heavy sprawl", "Using the free leg to clear the trap"]
  },
  {
    id: 131,
    name: "The Truck",
    category: "Leg Entanglement",
    aka: ["Wrestling leg ride"],
    skill_level: "Intermediate",
    gi_nogi: "No-gi recommended",
    risk_level: "Medium",
    body_target: "Hips / Spine",
    notes: "A 10th Planet signature position where you control the opponent's hips by scissoring one leg and hooking the other. An essential gateway to the Twister, calf slicers, and back takes.",
    common_setups: ["Rolling from top turtle position", "Transitioning from back control when the opponent slides out"],
    common_counters: ["Kicking the leg free before the lock", "Rolling aggressively through the position"]
  },
  {
    id: 132,
    name: "Crab Ride",
    category: "Position",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "Gi recommended",
    risk_level: "Medium",
    body_target: "Hips / Core",
    notes: "A dynamic back control position closely tied to the berimbolo, where you control the opponent's hips using both of your hooks positioned behind their knees, preventing them from turning to their back.",
    common_setups: ["Completing a berimbolo sweep", "Opponent defends a standard back take by turning face down"],
    common_counters: ["Pummeling legs inside to disrupt the hooks", "Rolling forward to break the grip structure"]
  },
  {
    id: 133,
    name: "S-Mount",
    category: "Position",
    aka: ["Technical S-Mount"],
    skill_level: "Intermediate",
    gi_nogi: "Both (Equally)",
    risk_level: "Medium",
    body_target: "Shoulders",
    notes: "A highly offensive variation of the mount where your legs form an 'S' shape, placing massive localized pressure on the opponent's chest and isolating an arm for an armbar.",
    common_setups: ["From high mount when the opponent tries to frame", "From technical mount sliding the back leg up"],
    common_counters: ["Preventing the leg slide with frames", "Explosive bridging before the weight settles"]
  },
  {
    id: 134,
    name: "Kesa-Gatame (Scarf Hold)",
    category: "Position",
    aka: ["Scarf hold"],
    skill_level: "Fundamental",
    gi_nogi: "Gi recommended",
    risk_level: "Medium",
    body_target: "Ribs / Core",
    notes: "A Judo-style side control holding the head and far arm tightly to the chest while spreading the legs for base. Creates immense chest pressure but exposes the back if the opponent slips the head.",
    common_setups: ["Finishing a Judo throw like O-goshi", "Transitioning smoothly from standard side control"],
    common_counters: ["Bridging and rolling over the holding arm", "Slipping the head out the back door"]
  },
  {
    id: 135,
    name: "Reverse Kesa-Gatame",
    category: "Position",
    aka: ["Twister side control"],
    skill_level: "Intermediate",
    gi_nogi: "Both (Equally)",
    risk_level: "Medium",
    body_target: "Hips",
    notes: "A side control variant facing the opponent's legs. Used to block knee-elbow escapes, set up far-side armbars, and transition to mount or leg entanglements.",
    common_setups: ["When opponent frames hard in standard side control", "Defending a hip escape"],
    common_counters: ["Pushing the hips away to recover guard", "Rolling away to turtle"]
  },
  {
    id: 136,
    name: "Buggy Choke",
    category: "Submission",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "High",
    body_target: "Neck",
    notes: "A highly unorthodox submission locked from bottom side control. The bottom player wraps their arm under their own leg to choke the top player. Extremely flexible practitioners benefit most.",
    common_setups: ["Opponent has heavy top side control and settles their head low", "When escaping side control seems impossible"],
    common_counters: ["Posturing up aggressively", "Framing on the neck/face to break the grip"]
  },
  {
    id: 137,
    name: "Aoki Lock",
    category: "Submission",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "High",
    body_target: "Ankle / Heel",
    notes: "A devastating rotational ankle-heel hybrid lock. Named after Shinya Aoki, it applies outward rotational pressure on the heel while gripping the toes similarly to a straight ankle lock.",
    common_setups: ["From standard Ashi Garami when straight ankle lock fails", "Entering into single leg X"],
    common_counters: ["Pummeling the foot to safety immediately", "Standing up to relieve pressure"]
  },
  {
    id: 138,
    name: "Barataplata",
    category: "Submission",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "Both (Equally)",
    risk_level: "Medium",
    body_target: "Shoulder / Bicep",
    notes: "A hybrid shoulder lock and bicep slicer executed typically by throwing your leg over the opponent's trapped arm while facing their legs. An explosive and unpredictable attack.",
    common_setups: ["When an opponent defends an omoplata", "From mount or triangle setups where the arm is pinned"],
    common_counters: ["Straightening the arm forcefully before the leg clears", "Hitching out the back door"]
  },
  {
    id: 139,
    name: "Monoplata",
    category: "Submission",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "Gi recommended",
    risk_level: "Medium",
    body_target: "Shoulder",
    notes: "Essentially an omoplata applied from top mount or side control rather than guard. The attacker uses their leg to apply immense rotational pressure to the shoulder while sitting back.",
    common_setups: ["From high mount when pinning one arm to the mat", "When an opponent defends an armbar by clasping hands"],
    common_counters: ["Keeping elbows tight to the ribs", "Rolling dynamically to relieve shoulder tension"]
  },
  {
    id: 140,
    name: "Banana Split",
    category: "Submission",
    aka: [],
    skill_level: "Unorthodox / Fun",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Groin / Hips",
    notes: "A painful groin/hip stretch submission from the 10th Planet system. Performed from the Truck position by pulling the opponent's legs apart in opposite directions.",
    common_setups: ["From the Truck position", "Rolling from a turtle breakdown"],
    common_counters: ["Preventing the secondary leg hook", "Rolling rapidly through the position"]
  },
  {
    id: 141,
    name: "Crotch Ripper",
    category: "Submission",
    aka: [],
    skill_level: "Unorthodox / Fun",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Groin / Hips",
    notes: "Similar to the Banana Split, this submission from the Truck isolates the far leg and uses both arms and legs to stretch the opponent's groin/hips to an unbearable degree.",
    common_setups: ["From the Truck position when the Banana Split fails", "Transitioning from back mount"],
    common_counters: ["Defending the hooks before the stretch begins", "Kicking the leg out forcefully"]
  },
  {
    id: 142,
    name: "Dead Orchard",
    category: "Submission",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "Medium",
    body_target: "Neck / Shoulders",
    notes: "A complex high-guard control (part of the Rubber Guard system) where the attacker locks a triangle over both of the opponent's shoulders, allowing for free armbars and chokes.",
    common_setups: ["From standard Rubber Guard / Mission Control", "When the opponent tries to stack out of a triangle"],
    common_counters: ["Posturing up extremely early", "Sprawling heavy on the hips to kill the guard elevation"]
  },
  {
    id: 143,
    name: "Texas Cloverleaf",
    category: "Submission",
    aka: [],
    skill_level: "Intermediate",
    gi_nogi: "No-gi recommended",
    risk_level: "High",
    body_target: "Knees / Calves",
    notes: "A powerful leg lock compression similar to a calf slicer but acting on both legs. You cross the opponent's legs over one another and apply downward pressure while locking your arms.",
    common_setups: ["From a failed straight ankle lock when the opponent brings in their other leg to defend", "From top half or side-saddle position"],
    common_counters: ["Prying the hands apart", "Hand-fighting to prevent the figure-four grip"]
  },
  {
    id: 144,
    name: "Crucifix Necktie (Short Choke)",
    category: "Submission",
    aka: ["Short Choke"],
    skill_level: "Intermediate",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Neck / Trachea",
    notes: "A rear naked choke variation applied when the forearm is across the throat rather than the deep bicep grip. Often applied from the crucifix or when the chin is tucked.",
    common_setups: ["From the back when the opponent heavily defends the deep RNC", "From the Crucifix position"],
    common_counters: ["Peeling the choking hand", "Turning the chin toward the choking arm"]
  },
  {
    id: 145,
    name: "Balloon Sweep (Overhead Sweep)",
    category: "Sweep",
    aka: ["Overhead Sweep"],
    skill_level: "Intermediate",
    gi_nogi: "Gi recommended",
    risk_level: "Medium",
    body_target: "Balance",
    notes: "Using the opponent's forward driving momentum to place a foot on their hips, fall backward, and launch them completely over your head into the mount position.",
    common_setups: ["From open/spider guard when the opponent drives forward aggressively", "Luring an opponent by playing a passive seated guard"],
    common_counters: ["Dropping hips backward immediately", "Base out with arms to avoid being flipped over"]
  },
  {
    id: 146,
    name: "Kiss of the Dragon",
    category: "Sweep",
    aka: ["Reverse DLR Spin Under"],
    skill_level: "Advanced",
    gi_nogi: "Both (Equally)",
    risk_level: "High",
    body_target: "Core / Hips",
    notes: "A flashy and powerful sweep from Reverse De La Riva guard where the bottom player spins entirely underneath the top player to emerge behind them to take the back.",
    common_setups: ["From Reverse De La Riva when the opponent tries to knee slice", "Baiting the knee slice pass on purpose"],
    common_counters: ["Dropping heavy into a smash pass instantly", "Backstepping to kill the RDLR hook"]
  },
  {
    id: 147,
    name: "Helicopter Sweep",
    category: "Sweep",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "Gi recommended",
    risk_level: "High",
    body_target: "Balance",
    notes: "A highly dynamic sweep similar to the balloon sweep, but rotating the opponent dramatically mid-air to land directly into a tight armbar.",
    common_setups: ["From open guard when controlling both sleeves and placing feet on hips", "Catching a strongly rushing passer"],
    common_counters: ["Breaking sleeve grips early", "Heavy hips and sprawling backward"]
  },
  {
    id: 148,
    name: "Sumi Gaeshi",
    category: "Takedown & Throw",
    aka: ["Corner Reversal"],
    skill_level: "Intermediate",
    gi_nogi: "Both (Equally)",
    risk_level: "Medium",
    body_target: "Balance",
    notes: "A classic sacrifice throw where the attacker drops to their back while inserting a butterfly hook to throw the forward-leaning opponent over their head.",
    common_setups: ["Defending a strong single leg takedown", "From a collar tie and overhook clinch"],
    common_counters: ["Posturing up and circling out", "Re-pummeling arms and sprawling"]
  },
  {
    id: 149,
    name: "Tomoe Nage",
    category: "Takedown & Throw",
    aka: ["Circle Throw"],
    skill_level: "Intermediate",
    gi_nogi: "Gi recommended",
    risk_level: "Medium",
    body_target: "Balance",
    notes: "A frontal sacrifice throw relying on strong lapel and sleeve grips. The attacker falls straight backward, placing a foot on the hip/groin to launch the opponent overhead.",
    common_setups: ["Breaking posture with strong collar grips", "Faking a forward judo throw then dropping back"],
    common_counters: ["Squatting down into a strong base", "Slipping off the foot hook by turning the hips"]
  },
  {
    id: 150,
    name: "Body Lock Pass",
    category: "Guard Pass",
    aka: ["Double under body lock"],
    skill_level: "Fundamental",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Hips",
    notes: "A crushing, low-risk pass where the top player locks their hands around the bottom player's waist (body lock), trapping their hips to the mat to slowly bypass the legs.",
    common_setups: ["From half guard top or butterfly guard", "When the bottom player sits up for a hook sweep"],
    common_counters: ["Heavy framing on the shoulders and neck", "Elevating with butterfly hooks before the hands clasp"]
  },
  {
    id: 151,
    name: "Float Pass",
    category: "Guard Pass",
    aka: ["Surfing pass"],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "High",
    body_target: "Core",
    notes: "A dynamic passing style relying on heavy chest pressure over the opponent's hips. The passer 'floats' their legs backward to kill the guard player's hooks and slides into side control or mount.",
    common_setups: ["When the opponent attempts butterfly or elevating sweeps", "Pummeling inside from a standing passing position"],
    common_counters: ["Off-balancing with strong underhooks", "Transitioning to single leg X under the float"]
  },
  {
    id: 152,
    name: "Folding Pass",
    category: "Guard Pass",
    aka: ["Smash Fold"],
    skill_level: "Intermediate",
    gi_nogi: "Both (Equally)",
    risk_level: "Low",
    body_target: "Legs / Knees",
    notes: "A high-pressure pass that involves forcing both of the opponent's knees to point in the same direction, turning their hips away and rendering their guard inactive.",
    common_setups: ["From Headquarters passing position", "Responding to a Z-guard or knee shield by smashing inward"],
    common_counters: ["Stiff-arming the passer's shoulder", "Heavily framing against the knee smash to retain the knee shield"]
  },
  {
    id: 153,
    name: "Backstep Pass",
    category: "Guard Pass",
    aka: [],
    skill_level: "Intermediate",
    gi_nogi: "No-gi recommended",
    risk_level: "Medium",
    body_target: "Hips",
    notes: "A fluid passer movement where the attacker turns their back to the opponent and steps their leg far away to clear the hooks. Critical gateway to the Saddle / Honey Hole positions.",
    common_setups: ["From top half guard passing", "When an opponent establishes a strong knee shield"],
    common_counters: ["Taking the back as they expose it", "Following the hips and locking into 50/50"]
  },
  {
    id: 154,
    name: "Leg Pin Pass (Staple Pass)",
    category: "Guard Pass",
    aka: ["Ruotolo Pass"],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "Medium",
    body_target: "Legs",
    notes: "Modernized dynamic passing largely popularized by the Ruotolo brothers, involving physically stepping on or pinning the opponent's legs/thighs with your shins to bypass the guard.",
    common_setups: ["From standing open guard when the opponent is supine", "Capitalizing on loose leg pummeling"],
    common_counters: ["Inverting rapidly", "Constantly circling the legs to prevent pins"]
  },
  {
    id: 155,
    name: "Russian Tie (2-on-1)",
    category: "Takedown & Throw",
    aka: [],
    skill_level: "Fundamental",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Shoulders",
    notes: "A fundamental wrestling grip where two hands control one of the opponent’s arms at the wrist and upper arm. Excellent for neutralizing offense and setting up single legs or lateral drops.",
    common_setups: ["Peeling a collar tie grip", "From neutral standing clinch exchanges"],
    common_counters: ["Limp-arming out of the grip", "Pummeling for an inside bicep tie"]
  },
  {
    id: 156,
    name: "Fireman's Carry (Kata Guruma)",
    category: "Takedown & Throw",
    aka: ["Kata Guruma"],
    skill_level: "Intermediate",
    gi_nogi: "Both (Equally)",
    risk_level: "Medium",
    body_target: "Core",
    notes: "A classic dump takedown where you drop underneath the opponent's arm, load them across your shoulders, and dump them to the far side.",
    common_setups: ["Off an opponent's high collar tie", "From an outside step fake single leg"],
    common_counters: ["Heavy sprawl and flattening out", "Guillotining the entering head"]
  },
  {
    id: 157,
    name: "Ankle Pick",
    category: "Takedown & Throw",
    aka: [],
    skill_level: "Intermediate",
    gi_nogi: "Both (Equally)",
    risk_level: "Low",
    body_target: "Ankle / Balance",
    notes: "A safe and effective takedown combining heavy downward pressure on the opponent’s head (collar tie) while reaching down to capture their leading ankle.",
    common_setups: ["Snap down from collar tie", "Fake double leg into ankle pick"],
    common_counters: ["Circling the lead leg back quickly", "Underhooking and sprawling"]
  },
  {
    id: 158,
    name: "Lateral Drop",
    category: "Takedown & Throw",
    aka: [],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "High",
    body_target: "Balance",
    notes: "A surprising upper-body sacrifice throw where you trap an overhook and an underhook, stepping deep and dropping to force the opponent gracefully over you.",
    common_setups: ["When the opponent is aggressively driving forward into an underhook", "Pummeling from an over-under clinch"],
    common_counters: ["Sinking hips and pulling back to avoid the throw", "Limp arm out of the overhook before the drop"]
  },
  {
    id: 159,
    name: "Mat Return",
    category: "Takedown & Throw",
    aka: ["Belly-to-back lift"],
    skill_level: "Fundamental",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Base",
    notes: "A wrestling staple where you trap the opponent's waist from their back. When they begin to stand, you lift them slightly and return them heavily to the mat to establish back control.",
    common_setups: ["When an opponent attempts a technical stand-up from turtle", "After escaping a bad position and taking a rear body lock"],
    common_counters: ["Base widening and heavy hips (sprawl weight down)", "Switching the hips vigorously"]
  },
  {
    id: 160,
    name: "Tai Otoshi",
    category: "Takedown & Throw",
    aka: ["Body Drop"],
    skill_level: "Intermediate",
    gi_nogi: "Gi recommended",
    risk_level: "Medium",
    body_target: "Balance",
    notes: "A powerful Judo hand throw where you step across the opponent's path and pull them strongly over your extended leg into a spinning fall.",
    common_setups: ["With a strong lapel and sleeve grip pulling forward", "Creating a reaction by faking backwards"],
    common_counters: ["Squatting deeply and maintaining rigid base", "Stepping over the blocking leg"]
  },
  {
    id: 161,
    name: "Kipping Escape",
    category: "Escape & Recovery",
    aka: ["Danaher Kipping Escape"],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "Medium",
    body_target: "Hips",
    notes: "A highly dynamic mount escape popularized by the Danaher/Gordon Ryan squad, utilizing an explosive kipping motion of the legs and hips to wedge frames in and enter directly into leg entanglements.",
    common_setups: ["Trapped in low heavy mount", "When standard bridge and roll escapes fail due to wide base"],
    common_counters: ["Establishing high mount under the armpits quickly", "Isolating one arm heavily to stop the kip rhythm"]
  },
  {
    id: 162,
    name: "Running Man Escape (Ghost Escape)",
    category: "Escape & Recovery",
    aka: ["Ghost Escape"],
    skill_level: "Intermediate",
    gi_nogi: "No-gi recommended",
    risk_level: "Low",
    body_target: "Shoulders / Hips",
    notes: "A slippery side control escape where you roll your hips entirely away from the opponent, presenting the back seemingly but quickly slipping underneath the cross-face to reset guard.",
    common_setups: ["Pinned under heavy side control pressure", "When turning into the opponent is blocked by bicep pins"],
    common_counters: ["Following closely immediately into back takes", "Crushing the hips with a heavy ride before the slip"]
  },
  {
    id: 163,
    name: "Heel Slip",
    category: "Escape & Recovery",
    aka: ["Late stage heel hook defense"],
    skill_level: "Advanced",
    gi_nogi: "No-gi recommended",
    risk_level: "Extremely High",
    body_target: "Heel",
    notes: "The primary micro-escape once a heel hook has correctly been applied and locked in. The trapped player physically points the toes and pries the heel out precisely before breaking pressure occurs.",
    common_setups: ["When ensnared deeply in a 50/50 or saddle heel hook", "As a last resort when positional escapes have failed"],
    common_counters: ["Re-gripping immediately to a higher fulcrum", "Switching to an Aoki lock or straight ankle"]
  }
];

const filePath = 'c:\\Users\\brima\\Documents\\Projects\\tapguard\\src\\components\\matrix\\BJJFlowBuilder.jsx';
let content = fs.readFileSync(filePath, 'utf8');

const regex = /(const DATA = \[\s*[\s\S]*?)(\n\];)/;
const match = content.match(regex);

if (match) {
  let newDataString = NEW_DATA.map(item => JSON.stringify(item, null, 2)).join(',\n    ');
  // inject a comma before the new data
  let updatedContent = content.replace(regex, `$1,\n    ${newDataString}$2`);
  fs.writeFileSync(filePath, updatedContent);
  console.log("Successfully added " + NEW_DATA.length + " techniques.");
} else {
  console.error("DATA array not found.");
}
